name: "Joel Califa is Sad"
description: "So Sad"

url: "http://localhost:4000"

paginate: 10

markdown: redcarpet
highlighter: pygments
permalink: pretty

picture:
  source: "/assets/images/"
  output: "/assets/images/generated"
  markup: "picture"
  presets:
    default:
      source_large:
        media: "(min-width: 45)"
        width: "880"
      source_medium:
        media: "(min-resolution: 45)"
        width: "640"
      source_default:
        width: "320"

